<!DOCTYPE html>
<html lang="pt_BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?=rcTitle(array(_('Associe-se'))); ?></title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="<?=base_url('vendor/almasaeed2010/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css');?>">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?=base_url('vendor/almasaeed2010/adminlte/dist/css/adminlte.min.css');?>">
</head>
<body class="hold-transition register-page pt-5 pr-5 pb-5 pl-5">

  <div class="card">
    <div class="card-body register-card-body">

        <h1 class="text-center">ESTATUTO DO R&Aacute;DIO CLUBE DE PELOTAS</h1>

        <!-- inicio do texto do estatuto - convertido com https://wordtohtml.net/ -->
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>&nbsp;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO PRIMEIRO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DA DENOMINA&Ccedil;&Atilde;O, F&Ocirc;RO, &Aacute;REA DE A&Ccedil;&Atilde;O, PRAZO E ANO SOCIAL</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 1&ordm; - O R&Aacute;DIO CLUBE DE PELOTAS, com a sigla RCP, rege-se pelo presente Estatuto e pelas disposi&ccedil;&otilde;es legais vigentes, tendo:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:43.4px;">
        <li><strong><span style='font-family:"Arial Narrow",sans-serif;'>F&ocirc;ro jur&iacute;dico</span></strong><span style='font-family:"Arial Narrow",sans-serif;'>&nbsp;na Comarca de Pelotas Estado do Rio Grande do Sul;</span></li>
        <li><strong><span style='font-family:"Arial Narrow",sans-serif;'>&Aacute;rea de a&ccedil;&atilde;o</span></strong><span style='font-family:"Arial Narrow",sans-serif;'>&nbsp;para efeito de admiss&atilde;o de associados, cuja denomina&ccedil;&atilde;o seja simplesmente s&oacute;cios, abrangendo a cidade de Pelotas, Estado do Rio Grande do Sul e demais munic&iacute;pios e Estados em todo o territ&oacute;rio nacional, para os s&oacute;cios denominados com caracter&iacute;sticas especiais, assim como, honor&aacute;rios, benem&eacute;ritos, etc....</span></li>
        <li><strong><span style='font-family:"Arial Narrow",sans-serif;'>Prazo de dura&ccedil;&atilde;o&nbsp;</span></strong><span style='font-family:"Arial Narrow",sans-serif;'>indeterminado e ano asocial compreendido no per&iacute;odo de 1&ordm; de janeiro a 31 de dezembro de cada ano.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO SEGUNDO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DOS OBJETIVOS SOCIAIS</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 2&ordm; - A sociedade objetiva, com base na colabora&ccedil;&atilde;o rec&iacute;proca, promover:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:43.25px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>A integra&ccedil;&atilde;o entre as pessoas diretamente ligadas, a r&aacute;dio emiss&atilde;o amador&iacute;stica, visando estreitar mais as rela&ccedil;&otilde;es de amizade e solidariedade entre elas;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>O relacionamento oficial com o Minist&eacute;rio das comunica&ccedil;&otilde;es, nos assuntos pertinentes ao Servi&ccedil;o R&aacute;dio: Amador e do Cidad&atilde;o, e de interesse dos seus associados;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>&nbsp;Coopera&ccedil;&atilde;o, com o Minist&eacute;rio das Comunica&ccedil;&otilde;es, para a fiel observ&acirc;ncia, pelos seus associados, das normas pertinentes ao Servi&ccedil;o R&aacute;dio: Amador e do Cidad&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>A representa&ccedil;&atilde;o do Minist&eacute;rio das Comunica&ccedil;&otilde;es, quando comprovada a pr&aacute;tica de infra&ccedil;&atilde;o cometida por usu&aacute;rios do servi&ccedil;o, prevista na legisla&ccedil;&atilde;o espec&iacute;fica;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>A promo&ccedil;&atilde;o, por todos os meios a seu alcance, do aprimoramento dos conhecimentos t&eacute;cnicos dos seus associados, e a divulga&ccedil;&atilde;o de instru&ccedil;&otilde;es que visem a utiliza&ccedil;&atilde;o racional e eficiente dos canais e faixas destinadas ao Servi&ccedil;o R&aacute;dio: Amador e do Cidad&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>A manuten&ccedil;&atilde;o, sempre que poss&iacute;vel, de esta&ccedil;&otilde;es destinadas a escuta dos chamados de emerg&ecirc;ncia no canal 09;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>O esclarecimento da opini&atilde;o p&uacute;blica sobre as fun&ccedil;&otilde;es sociais da r&aacute;dio emiss&atilde;o amador&iacute;stica e sobre os servi&ccedil;os prestados &agrave; coletividade;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Entre seus objetivos principais, o desenvolvimento de atividades de utilidade p&uacute;blica, cooperando com os poderes p&uacute;blicos, associa&ccedil;&otilde;es de classes e quaisquer outras institui&ccedil;&otilde;es em tudo que interessa direta ou indiretamente a seus associados;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Fornecer ao Minist&eacute;rio das Comunica&ccedil;&otilde;es as informa&ccedil;&otilde;es que se fizerem necess&aacute;rias sobre as atividades de seus associados no que se refere &agrave; execu&ccedil;&atilde;o do servi&ccedil;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Entre os componentes do Clube a realiza&ccedil;&atilde;o de cursos e a permuta de informa&ccedil;&otilde;es, visando a melhoria dos conhecimentos t&eacute;cnicos especializados;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>A recrea&ccedil;&atilde;o e o lazer;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Toda e qualquer atividade que n&atilde;o conflite com o presente Estatuto e a legisla&ccedil;&atilde;o em vigor;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>O Clube representar&aacute; oficial e extraoficialmente os seus s&oacute;cios e proponentes, junto ao Departamento Nacional de Telecomunica&ccedil;&otilde;es, em conson&acirc;ncia com o artigo 3&ordm;&nbsp;</span><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-family:"Arial Narrow",sans-serif;font-size:10.5pt;'>&sect; 2&ordm;;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Assist&ecirc;ncia social;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Solicitar ao Minist&eacute;rio das Comunica&ccedil;&otilde;es todos os elementos que dele dependam para a completa realiza&ccedil;&atilde;o de suas finalidades.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO TERCEIRO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DOS ASSOCIADOS &ndash; DIREITOS &nbsp;- DEVERES - RESPONSABILIDADES</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 3&ordm; - Poder&aacute; ingressar ao Clube, salvo se houver impossibilidade legal, qualquer pessoa f&iacute;sica que se dedique &agrave; atividade de r&aacute;dio emiss&atilde;o amadora em qualquer faixa, compreendida entre os dois metros e os cento e sessenta metros, ou outras que venham a ser aprovadas pelos &oacute;rg&atilde;os competentes, que concordem com as disposi&ccedil;&otilde;es deste Estatuto.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:53.25pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>&nbsp;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:53.25pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 1&ordm; - No ato do ingresso, o interessado comprovar&aacute; a sua condi&ccedil;&atilde;o de r&aacute;dio operador;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:53.25pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 2&ordm; - N&atilde;o possuindo ainda seu registro legal, poder&aacute; o Clube favorecer o encaminhamento de seus documentos, bem como prestar informa&ccedil;&otilde;es e promover cursos sobre o uso do r&aacute;dio;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:53.25pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 3&ordm; - O n&uacute;mero de associados n&atilde;o ter&aacute; limite quanto ao m&aacute;ximo.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 4&ordm; - Para associar-se o interessado preencher&aacute; a proposta fornecida pelo Clube que ap&oacute;s aprovada pela Diretoria, considerar-se-&aacute; admitido ao Clube.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 5&ordm; - Cumprindo o que disp&otilde;e o artigo anterior, o associados adquire todos os direitos e assume todos os deveres e decorrentes da Lei, deste estatuto e das delibera&ccedil;&otilde;es tomadas pelo Clube.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-indent:35.4pt;'><span style='font-family:"Arial Narrow",sans-serif;'>I &ndash; O associado tem direito a:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Tomar parte nas assembleias gerais, discutindo e votando os assuntos que nela se tratarem, ressalvados os casos tratados no artigo 15&ordm;;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Votar e ser votado para a Diretoria ou membro do &nbsp; Conselho Deliberativo;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Propor &agrave; Diretoria, Conselho Deliberativo ou as &agrave;s assembleias gerais, medidas de interesse do Clube;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Demitir-se da sociedade quando lhe convier;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Promover com o Clube as atividades que constituem seu objetivo;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Consultar, no m&ecirc;s que antecede a Assembleia Geral Ordin&aacute;ria, os livros e pe&ccedil;as do balan&ccedil;o geral.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>II &ndash; S&atilde;o deveres dos s&oacute;cios:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Cumprir as disposi&ccedil;&otilde;es da Lei, do Estatuto, respeitar resolu&ccedil;&otilde;es regularmente tomadas pela Diretoria, Conselho Deliberativo e Assembleias Gerais;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Satisfazer pontualmente suas mensalidades e taxas, previamente determinadas pela Diretoria e Conselho Deliberativo;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Zelar pelo bom nome do Clube e da classe de r&aacute;dio-operadores amadores.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>III &ndash; Os s&oacute;cios em geral n&atilde;o respondem subsidiariamente pelas obriga&ccedil;&otilde;es sociais.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO QUARTO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DA DEMISS&Atilde;O, ELIMINA&Ccedil;&Atilde;O E EXCLUS&Atilde;O</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 6&ordm; - A demiss&atilde;o de associado, que n&atilde;o poder&aacute; ser negada, dar-se-&aacute; unicamente a seu pedido, por escrito, em requerimento ao Presidente, devendo ser averbado em livro pr&oacute;prio.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 7&ordm; - A elimina&ccedil;&atilde;o do associado, que ser&aacute; aplicada em virtude de infra&ccedil;&atilde;o da Lei, ou deste Estatuto, ser&aacute; feita por decis&atilde;o do Conselho Deliberativo depois de notificado ao infrator os motivos que a determinaram dever&atilde;o constar no livro pr&oacute;prio.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 8&ordm; - A exclus&atilde;o do associado ser&aacute; feita:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Por dissolu&ccedil;&atilde;o da pessoa jur&iacute;dica;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Por morte da pessoa f&iacute;sica;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Por deixar de atender os requisitos estatut&aacute;rios de ingresso ou perman&ecirc;ncia no Clube.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.25pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; &Uacute;nico &ndash; A exclus&atilde;o do associado, com fundamento nas disposi&ccedil;&otilde;es do item &ldquo;c&rdquo; deste artigo, dever&aacute; ser feita por decis&atilde;o do Conselho Deliberativo, aplicando-se no caso, o disposto no artigo 7&ordm;. Ser&aacute; ressalvado ao associado o direito de defender-se em um prazo de quinze dias.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO QUINTO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DA ASSEMBL&Eacute;IA GERAL</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 9&ordm; - A assembleia geral dos associados, ordin&aacute;ria ou extraordin&aacute;ria, &eacute; o &oacute;rg&atilde;o supremo do Clube, dentro dos limites da Lei e deste Estatuto e tomar&aacute; toda e qualquer decis&atilde;o de interesse da sociedade e sua delibera&ccedil;&atilde;o vinculam a todos, ainda que ausentes ou discordantes.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 10&ordm; - A Assembleia Geral, ordin&aacute;ria ou extraordin&aacute;ria, dever&aacute; ser aberta pelo Presidente ou seu representante legal que indicar&aacute; um membro dos presentes para dirigir os trabalhos, convidando este um associado para secret&aacute;rio.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-indent:35.4pt;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 1&ordm; &nbsp;- Poder&aacute; tamb&eacute;m ser convocada por 1/5 (um quinto) dos associados em pleno gozo de seus direitos sociais, ap&oacute;s solicita&ccedil;&atilde;o n&atilde;o atendida;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-indent:35.4pt;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 2&ordm; &nbsp;- N&atilde;o poder&aacute; participar da Assembleia Geral o associado que:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Tenha sido admitido ap&oacute;s sua convoca&ccedil;&atilde;o;</span></li>
        <li><span style='line-height:107%;font-family:"Arial Narrow",sans-serif;font-size:14px;'>Esteja na infring&ecirc;ncia de qualquer disposi&ccedil;&atilde;o do item II, do artigo 5&ordm;.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 11&ordm; - Em qualquer das hip&oacute;teses referidas no artigo anterior, as Assembleias Gerais ser&atilde;o convocadas com anteced&ecirc;ncia m&iacute;nima de 15 (quinze) dias para a primeira reuni&atilde;o, de uma hora para a segunda e uma hora para a terceira;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-indent:35.4pt;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; &Uacute;nico &nbsp;- As tr&ecirc;s reuni&otilde;es poder&atilde;o ser convocadas num &uacute;nico edital, desde que dele conste, expressamente, os prazos para cada uma delas.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 12&ordm; - Dos editais de convoca&ccedil;&atilde;o das Assembleias Gerais dever&atilde;o constar:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>A denomina&ccedil;&atilde;o do Clube, seguido da express&atilde;o &ldquo;Convoca&ccedil;&atilde;o da Assembleia Geral&rdquo;, ordin&aacute;ria ou extraordin&aacute;ria, conforme o caso;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>O dia e a hora da reuni&atilde;o, em cada convoca&ccedil;&atilde;o, assim como o endere&ccedil;o do local de sua realiza&ccedil;&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>A sequ&ecirc;ncia ordinal das convoca&ccedil;&otilde;es;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>A ordem do dia dos trabalhos, com as devidas especifica&ccedil;&otilde;es;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>O n&uacute;mero de associados existentes da data de sua expedi&ccedil;&atilde;o, para efeito de c&aacute;lculo do &ldquo;qu&oacute;rum&rdquo; de instala&ccedil;&atilde;o;</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-indent:35.4pt;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 1 &ndash; No caso de a convoca&ccedil;&atilde;o ser feita por associados, o Edital ser&aacute; assinado, no m&iacute;nimo pelos quatro primeiros signat&aacute;rios do documento que a solicitou;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-indent:35.4pt;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 2 &ndash; Os editais de convoca&ccedil;&atilde;o poder&atilde;o ser publicados em jornais ou comunicados por circulares aos associados, mediante protocolo. &nbsp;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 13&ordm; - O &ldquo;quorum&rdquo; para instala&ccedil;&atilde;o da Assembleia Geral, &eacute; o seguinte:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>2/3 (dois ter&ccedil;os) do n&uacute;mero de associados, em condi&ccedil;&otilde;es de votar, em primeira convoca&ccedil;&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Metade mais 1 (um) dos associados em segunda convoca&ccedil;&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>M&iacute;nimo de 10 (dez) associados, na terceira convoca&ccedil;&atilde;o.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 14&ordm; - Os trabalhos das Assembleias Gerais ser&atilde;o dirigidos pelo Presidente, auxiliado pelo Secret&aacute;rio do Clube, sendo por aquele convidado a participar da Mesa os ocupantes de cargos sociais presentes.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 15&ordm; - Os ocupantes de cargos sociais, como quaisquer outros associados, n&atilde;o poder&atilde;o votar nas decis&otilde;es sobre os assuntos que a eles se refiram de maneira direta ou indireta, mas n&atilde;o ficar&atilde;o privados de tomar parte nos debates respectivos.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 16&ordm; - Nas Assembleias Gerais em que forem discutidos os balan&ccedil;os das contas, o Presidente do Clube, logo ap&oacute;s a leitura do relat&oacute;rio da gest&atilde;o, solicitar&aacute; ao plen&aacute;rio que indique um associado para coordenar os debates e a vota&ccedil;&atilde;o da mat&eacute;ria.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 17&ordm; - O coordenador indicado escolher&aacute; um secret&aacute;rio para auxilia-lo na reda&ccedil;&atilde;o das decis&otilde;es a serem inclu&iacute;das na Ata, pelo Secret&aacute;rio da Assembleia.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO SEXTO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DA ASSEMBL&Eacute;IA GERAL ORDIN&Aacute;RIA</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 18&ordm; - A Assembleia Geral Ordin&aacute;ria, que se realizar&aacute; obrigatoriamente uma vez por ano, no decorrer do m&ecirc;s de mar&ccedil;o, deliberar&aacute; sobre os seguintes assuntos:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:43.25px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Presta&ccedil;&atilde;o de contas, relat&oacute;rio da gest&atilde;o, balan&ccedil;o e plano de atividades para o exerc&iacute;cio seguinte;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Elei&ccedil;&atilde;o dos componentes da Diretoria e do Conselho Deliberativo;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Quaisquer assuntos de interesse social exclu&iacute;dos os enumerados no artigo 20 deste Estatuto.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO S&Eacute;TIMO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DA ASSEMBL&Eacute;IA GERAL EXTRAORDIN&Aacute;RIA</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 19&ordm; &ndash; A Assembleia Geral Extraordin&aacute;ria, realizar-se-&aacute; sempre que necess&aacute;rio e poder&aacute; deliberar sobre qualquer assunto de interesse da sociedade, desde que, mencionado no Edital de Convoca&ccedil;&atilde;o.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 20&ordm; - &Eacute; de compet&ecirc;ncia exclusiva da Assembleia Geral Extraordin&aacute;ria deliberar sobre os seguintes assuntos:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:78.8px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Reforma do estatuto;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Dissolu&ccedil;&atilde;o da sociedade.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-indent:35.25pt;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; &Uacute;nico &ndash; S&atilde;o necess&aacute;rios os votos de 2/3 (dois ter&ccedil;os) dos associados presentes, para tornar v&aacute;lidas as delibera&ccedil;&otilde;es de que trata este artigo.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO OITAVO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DA DIRETORIA E CONSELHO DELIBERATIVO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 21&ordm; - O Clube ser&aacute; administrado pelo seguintes &oacute;rg&atilde;os:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.5px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Diretoria;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Conselho Deliberativo.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 22&ordm; - A diretoria ser&aacute; composta de 7 (sete) membros, sendo:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Presidente;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>1&ordm; Vice-Presidente;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>2&ordm; Vice-Presidente;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Secret&aacute;rio;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Vice-secret&aacute;rio;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Tesoureiro;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Vice-tesoureiro;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Diretor de Rela&ccedil;&otilde;es P&uacute;blicas, Diretor de Patrim&ocirc;nio e Consultor Jur&iacute;dico s&atilde;o cargos de confian&ccedil;a da Presid&ecirc;ncia.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 23&ordm; - O mandato da Diretoria ser&aacute; de um ano, podendo ser reeleita no seu todo ou parcialmente.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 24&ordm; - No caso de algum membro da Diretoria ou do Conselho Deliberativo n&atilde;o desejar participar do exerc&iacute;cio seguinte, dever&aacute; comunicar aos outros membros sua decis&atilde;o, por escrito e com uma anteced&ecirc;ncia m&iacute;nima de 30 (trinta) dias &agrave; convoca&ccedil;&atilde;o da Assembleia.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 25&ordm; - O mandato do Conselho Deliberativo tamb&eacute;m ser&aacute; de um ano e dentro dos mesmos crit&eacute;rios do artigo 23&ordm; deste Estatuto.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 26&ordm; - Ao Presidente cabe, entre outras, as seguintes atribui&ccedil;&otilde;es:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Representar o Clube em ju&iacute;zo ou fora dele;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Convocar e presidir as reuni&otilde;es de Diretoria;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Designar atribui&ccedil;&otilde;es e servi&ccedil;os de car&aacute;ter funcional no desempenho das atividades sociais.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 27&ordm; - Ao Secret&aacute;rio compete:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.8px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Dirigir e coordenar os trabalhos da secretaria;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Secretariar as reuni&otilde;es;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Colaborar na programa&ccedil;&atilde;o de todas atividades.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 28&ordm; - Ao Tesoureiro compete:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.8px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Dirigir e coordenar os trabalhos da tesouraria;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Manter registro cont&aacute;bil e financeiro de toda a organiza&ccedil;&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Promover balancetes demonstrativos mensais e anuais.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 29&ordm; - Aos vices eleitos, compete a substitui&ccedil;&atilde;o dos respectivos titulares em suas aus&ecirc;ncias, e ainda sua participa&ccedil;&atilde;o em todas promo&ccedil;&otilde;es.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 30&ordm; - Ao Diretor de Rela&ccedil;&otilde;es P&uacute;blicas compete:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.65px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Promover campanhas e movimentos sociais, de car&aacute;ter amistoso ou cumulativo;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Programar festividades e recep&ccedil;&otilde;es, divulgando o Clube e mantendo interc&acirc;mbio com outras organiza&ccedil;&otilde;es de car&aacute;ter semelhante.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 31&ordm; - Ao Diretor de Patrim&ocirc;nio compete:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:78.8px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Determinar que se mantenha em dia o registro de todos os bens do Clube, quer m&oacute;veis, utens&iacute;lios ou im&oacute;veis, os quais ser&atilde;o catalogados ou descritos em livro de invent&aacute;rio especialmente confeccionado para este fim, devendo tal registro ser feito por ordem alfab&eacute;tica de esp&eacute;cie;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Providenciar a numera&ccedil;&atilde;o por ordem crescente, com chapa de metal ou tinta indel&eacute;vel, dos m&oacute;veis e instala&ccedil;&otilde;es e outros bens suscet&iacute;veis de receberem numera&ccedil;&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Apresentar por escrito semestralmente, &agrave; Diretoria, uma descri&ccedil;&atilde;o das ocorr&ecirc;ncias verificadas, no movimento dos bens do Clube, mencionando as faltas, avarias novas aquisi&ccedil;&otilde;es ou quaisquer outras altera&ccedil;&otilde;es porventura verificadas;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Organizar, no fim do per&iacute;odo administrativo, o balan&ccedil;o patrimonial, descrevendo minuciosamente todos os bens e respectivos valores, inscrevendo em folhas especiais, a fim de que possa ser anexado ao Relat&oacute;rio da Diretoria.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 32&ordm; - Ao Consultor Jur&iacute;dico compete:</span></p>
        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
        <ol start="1" style="margin-bottom:0cm;list-style-type: lower-alpha;margin-left:78.65px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Aconselhar-se juridicamente quando o caso em quest&atilde;o assim o requerer.</span></li>
        </ol>
        </div>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 33&ordm; - O Conselho Deliberativo ser&aacute; composto de cinco membros efetivos e dois suplentes, eleitos para o mesmo per&iacute;odo da Diretoria na mesma elei&ccedil;&atilde;o e com candidatos individuais.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 34&ordm; - Considerar-se-&atilde;o eleitos os efetivos, os cinco primeiros mais votados, sendo os dois seguintes para suplentes.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 35&ordm; - No afastamento de qualquer membro do Conselho, o primeiro suplente mais votado ser&aacute; convocado.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 36&ordm; - Ao Conselho Deliberativo compete, entre outras:</span></p>
        <ol class="decimal_type" start="1" style="list-style-type: lower-alpha;margin-left:43.4px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Eleger seu Presidente e Secret&aacute;rio;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Estabelecer normas de conduta de suas reuni&otilde;es;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Sugerir programas ao Clube &nbsp;e fiscalizar os trabalhos da Diretoria, apresentando sugest&otilde;es, ou solicitando esclarecimentos;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Estabelecer em instru&ccedil;&otilde;es ou regulamentos san&ccedil;&otilde;es ou penalidades a serem aplicadas nos casos de viola&ccedil;&atilde;o ou abuso cometidos contra disposi&ccedil;&otilde;es da Lei, deste Estatuto ou das regras de relacionamento com a sociedade, que venham a ser expedidas de suas reuni&otilde;es.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 37&ordm; - O Conselho Deliberativo re&uacute;ne-se ordinariamente semestralmente e extraordinariamente sempre que necess&aacute;rio, por convoca&ccedil;&atilde;o de seu Presidente, da maioria do pr&oacute;prio Conselho, ou ainda, por solicita&ccedil;&atilde;o de qualquer membro da Diretoria.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 1 &ndash; Deliberar validamente com a presen&ccedil;a de no m&iacute;nimo, tr&ecirc;s conselheiros no gozo de seus direitos.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; 2 &ndash; As delibera&ccedil;&otilde;es ser&atilde;o consignadas em Atas circunstanciadas, lavradas no livro pr&oacute;prio, lidas, aprovadas e assinadas ao final dos trabalhos.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 38&ordm; - Cabe &agrave; Diretoria reunir-se uma vez por m&ecirc;s ordinariamente e extraordinariamente sempre que necess&aacute;rio, por convoca&ccedil;&atilde;o do Presidente, do Conselho Deliberativo ou de qualquer outro membro da Diretoria, quando necess&aacute;rio for.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 39</span><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&nbsp;&ndash; Perder&aacute; automaticamente o cargo, o membro da Diretoria que, sem justificativa, faltar a 3 (tr&ecirc;s) reuni&otilde;es ordin&aacute;rias consecutivas ou a 6 (seis) alternadas, durante o ano.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&nbsp;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO NONO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DOS LIVROS</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>Art. 40&ordm; - O Clube dever&aacute; ter os seguintes livros:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:43.25px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Livro de Atas das Assembleias Gerais;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Livro de Atas das Reuni&otilde;es da Diretoria;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Livro de Atas do Conselho Deliberativo;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Livro de Presen&ccedil;a das Assembleias Gerais;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Livro de Presen&ccedil;a das Reuni&otilde;es da Diretoria;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Livro de Presen&ccedil;a do Conselho Deliberativo;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Livro de matr&iacute;cula, demiss&atilde;o, elimina&ccedil;&atilde;o e exclus&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Livro de Patrim&ocirc;nio;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Outros fiscais e cont&aacute;beis obrigat&oacute;rios.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.25pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&sect; &Uacute;nico &ndash; &Eacute; facultada a ado&ccedil;&atilde;o de livros de folhas soltas ou fichas.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 41&ordm;</span><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&nbsp;&ndash; No livro de matr&iacute;cula os associados ser&atilde;o inscritos por ordem cronol&oacute;gica de admiss&atilde;o e dele dever&aacute; constar:</span></p>
        <ol start="1" style="list-style-type: lower-alpha;margin-left:43.4px;">
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Prefixo e indicativo fornecidos pelo DENTEL;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Qualifica&ccedil;&atilde;o;</span></li>
        <li><span style='font-family:"Arial Narrow",sans-serif;'>Data de sua admiss&atilde;o, demiss&atilde;o, elimina&ccedil;&atilde;o ou exclus&atilde;o.</span></li>
        </ol>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:53.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>&nbsp;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>CAPITULO D&Eacute;CIMO</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial Narrow",sans-serif;'>DISPOSI&Ccedil;&Otilde;ES GERAIS E TRANSIT&Oacute;RIAS</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:14px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 42&ordm;</span><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&nbsp;&ndash; O mandato de ocupantes de cargos na Diretoria e Conselho Deliberativo, perdura at&eacute; a realiza&ccedil;&atilde;o da sess&atilde;o ordin&aacute;ria da Assembleia Geral que corresponde ao ano social em que tais mandatos findam.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 43&ordm; - Para que n&atilde;o fique ac&eacute;fala a administra&ccedil;&atilde;o do Clube, os membros da Diretoria e Conselho continuar&atilde;o nos respectivos cargos at&eacute; que a Assembleia Geral lhes d&ecirc; substitutos.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Art. 44&ordm; - No caso de extin&ccedil;&atilde;o do Clube como pessoa jur&iacute;dica, quer por senten&ccedil;a judicial ou delibera&ccedil;&atilde;o por Assembleia Geral Extraordin&aacute;ria, com o m&iacute;nimo de 2/3 (dois ter&ccedil;os) dos associados presentes, o &ldquo;Patrim&ocirc;nio Social&rdquo; passar&aacute; &agrave; entidade cong&ecirc;nere, devidamente registrada no CNSS, Conselho Nacional de Servi&ccedil;o Social.</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Pelotas, 12 de julho de 1980</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Presidente &nbsp;da Assembleia: Ricardo Gurvitz<br>&nbsp;Secret&aacute;rio da Assembleia: Osmar do Prado e Silva</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>&nbsp;</span></p>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:107%;font-family:"Arial Narrow",sans-serif;'>Dr. Nede Emilio da Silva<br>&nbsp;OAB 8900 &ndash; CPF 065.698.460-00</span></p>


         <!-- final do texto do estatuto - convertido com https://wordtohtml.net/ -->
 
    </div>
    <!-- /.form-box -->
  </div>

  <!-- AdminLTE App -->
  <script src="<?=base_url('vendor/components/jquery/jquery.min.js')?>"></script>
  <script src="<?=base_url('vendor/almasaeed2010/adminlte/dist/js/adminlte.min.js')?>"></script>
</body>
</html>

